import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAccount,
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { expect } from "chai";

// Type will be generated by `anchor build`
type Escrow = any;

describe("escrow", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.Escrow as Program<Escrow>;
  const authority = provider.wallet as anchor.Wallet;

  let tokenMint: anchor.web3.PublicKey;
  let funderTokenAccount: anchor.web3.PublicKey;
  let winnerKeypair: anchor.web3.Keypair;
  let winnerTokenAccount: anchor.web3.PublicKey;
  let treasuryKeypair: anchor.web3.Keypair;
  let treasuryTokenAccount: anchor.web3.PublicKey;

  const bountyId = new anchor.BN(1);
  const escrowAmount = new anchor.BN(1_000_000_000); // 1B base units

  // Derive PDAs
  const [escrowPda] = anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("escrow"), bountyId.toArrayLike(Buffer, "le", 8)],
    program.programId
  );
  const [escrowVaultPda] = anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("escrow_vault"), bountyId.toArrayLike(Buffer, "le", 8)],
    program.programId
  );

  before(async () => {
    winnerKeypair = anchor.web3.Keypair.generate();
    treasuryKeypair = anchor.web3.Keypair.generate();

    // Airdrop SOL for rent
    const airdropSig = await provider.connection.requestAirdrop(
      winnerKeypair.publicKey,
      2 * anchor.web3.LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropSig);

    // Create $FNDRY mint
    tokenMint = await createMint(
      provider.connection,
      (authority as any).payer,
      authority.publicKey,
      null,
      9 // 9 decimals
    );

    // Create funder ATA and mint tokens
    funderTokenAccount = await createAssociatedTokenAccount(
      provider.connection,
      (authority as any).payer,
      tokenMint,
      authority.publicKey
    );

    await mintTo(
      provider.connection,
      (authority as any).payer,
      tokenMint,
      funderTokenAccount,
      authority.publicKey,
      10_000_000_000 // 10B tokens
    );
  });

  it("initializes escrow and deposits tokens", async () => {
    await program.methods
      .initialize(bountyId, escrowAmount)
      .accounts({
        funder: authority.publicKey,
        escrow: escrowPda,
        tokenMint,
        funderTokenAccount,
        escrowVault: escrowVaultPda,
        systemProgram: anchor.web3.SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .rpc();

    // Verify escrow account
    const escrow = await program.account.escrow.fetch(escrowPda);
    expect(escrow.bountyId.toNumber()).to.equal(1);
    expect(escrow.funder.toBase58()).to.equal(authority.publicKey.toBase58());
    expect(escrow.amount.toNumber()).to.equal(1_000_000_000);
    expect(escrow.status).to.deep.equal({ funded: {} });

    // Verify vault has tokens
    const vault = await getAccount(provider.connection, escrowVaultPda);
    expect(Number(vault.amount)).to.equal(1_000_000_000);
  });

  it("releases escrow to winner with 5% fee", async () => {
    // Winner and treasury ATAs will be created by init_if_needed
    winnerTokenAccount = anchor.utils.token.associatedAddress({
      mint: tokenMint,
      owner: winnerKeypair.publicKey,
    });
    treasuryTokenAccount = anchor.utils.token.associatedAddress({
      mint: tokenMint,
      owner: treasuryKeypair.publicKey,
    });

    await program.methods
      .release(bountyId)
      .accounts({
        authority: authority.publicKey,
        escrow: escrowPda,
        escrowVault: escrowVaultPda,
        winner: winnerKeypair.publicKey,
        winnerTokenAccount,
        treasury: treasuryKeypair.publicKey,
        treasuryTokenAccount,
        tokenMint,
        systemProgram: anchor.web3.SystemProgram.programId,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
      })
      .rpc();

    // Verify escrow is released
    const escrow = await program.account.escrow.fetch(escrowPda);
    expect(escrow.status).to.deep.equal({ released: {} });

    // Verify winner got 95%
    const winnerAta = await getAccount(provider.connection, winnerTokenAccount);
    const expectedPayout = 950_000_000; // 95% of 1B
    expect(Number(winnerAta.amount)).to.equal(expectedPayout);

    // Verify treasury got 5%
    const treasuryAta = await getAccount(
      provider.connection,
      treasuryTokenAccount
    );
    const expectedFee = 50_000_000; // 5% of 1B
    expect(Number(treasuryAta.amount)).to.equal(expectedFee);
  });

  it("closes escrow after release", async () => {
    await program.methods
      .close(bountyId)
      .accounts({
        authority: authority.publicKey,
        funder: authority.publicKey,
        escrow: escrowPda,
        escrowVault: escrowVaultPda,
        tokenMint,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    // Verify escrow account is closed
    try {
      await program.account.escrow.fetch(escrowPda);
      expect.fail("Should have thrown - account closed");
    } catch (e: any) {
      expect(e.message).to.include("Account does not exist");
    }
  });

  describe("refund flow", () => {
    const refundBountyId = new anchor.BN(2);
    const refundAmount = new anchor.BN(500_000_000);

    const [refundEscrowPda] = anchor.web3.PublicKey.findProgramAddressSync(
      [
        Buffer.from("escrow"),
        refundBountyId.toArrayLike(Buffer, "le", 8),
      ],
      program.programId
    );
    const [refundVaultPda] = anchor.web3.PublicKey.findProgramAddressSync(
      [
        Buffer.from("escrow_vault"),
        refundBountyId.toArrayLike(Buffer, "le", 8),
      ],
      program.programId
    );

    it("initializes escrow for refund test", async () => {
      await program.methods
        .initialize(refundBountyId, refundAmount)
        .accounts({
          funder: authority.publicKey,
          escrow: refundEscrowPda,
          tokenMint,
          funderTokenAccount,
          escrowVault: refundVaultPda,
          systemProgram: anchor.web3.SystemProgram.programId,
          tokenProgram: TOKEN_PROGRAM_ID,
          rent: anchor.web3.SYSVAR_RENT_PUBKEY,
        })
        .rpc();
    });

    it("refunds tokens back to funder", async () => {
      const balanceBefore = await getAccount(
        provider.connection,
        funderTokenAccount
      );

      await program.methods
        .refund(refundBountyId)
        .accounts({
          authority: authority.publicKey,
          funder: authority.publicKey,
          escrow: refundEscrowPda,
          escrowVault: refundVaultPda,
          funderTokenAccount,
          tokenMint,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .rpc();

      const balanceAfter = await getAccount(
        provider.connection,
        funderTokenAccount
      );
      expect(Number(balanceAfter.amount) - Number(balanceBefore.amount)).to.equal(
        500_000_000
      );

      const escrow = await program.account.escrow.fetch(refundEscrowPda);
      expect(escrow.status).to.deep.equal({ refunded: {} });
    });

    it("rejects double refund", async () => {
      try {
        await program.methods
          .refund(refundBountyId)
          .accounts({
            authority: authority.publicKey,
            funder: authority.publicKey,
            escrow: refundEscrowPda,
            escrowVault: refundVaultPda,
            funderTokenAccount,
            tokenMint,
            tokenProgram: TOKEN_PROGRAM_ID,
          })
          .rpc();
        expect.fail("Should have thrown");
      } catch (e: any) {
        expect(e.toString()).to.include("InvalidStatus");
      }
    });
  });
});
